<?php
// File: inc/enqueue-fonts.php
/**
 * Resolve a theme font stylesheet URL.
 *
 * Priority:
 * 1) Local hosted Google Fonts CSS generated by WP Rocket (if it exists)
 * 2) Direct Google Fonts URL (fallback)
 *
 * @return array{0:string,1:string|int|null,2:bool} [url, version, is_local]
 */
function matrix_starter_resolve_font_stylesheet(): array {
  $google_url = 'https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Playfair:ital,opsz,wght@0,5..1200,300..900;1,5..1200,300..900&family=Great+Vibes:wght@400&display=swap';

  $matches = glob(WP_CONTENT_DIR . '/cache/fonts/*/google-fonts/css/*/*/*/*.css');
  if (is_array($matches) && !empty($matches)) {
    usort($matches, static function ($a, $b) {
      return filemtime($b) <=> filemtime($a);
    });
    $local_file = $matches[0];
    if (is_string($local_file) && file_exists($local_file)) {
      $relative = str_replace(WP_CONTENT_DIR, '', $local_file);
      $url = content_url($relative);
      return [$url, filemtime($local_file), true];
    }
  }

  return [$google_url, null, false];
}

/**
 * Enqueue theme fonts from local hosted CSS (if available) or Google.
 */
function matrix_starter_enqueue_fonts() {
  [$font_url, $font_ver] = matrix_starter_resolve_font_stylesheet();
  wp_enqueue_style('matrix-theme-fonts', $font_url, [], $font_ver);
}
add_action('wp_enqueue_scripts', 'matrix_starter_enqueue_fonts', 5);

/**
 * Optional: Resource hints for Google Fonts only when external URL is used.
 */
function matrix_starter_resource_hints($hints, $relation_type) {
  [, , $is_local] = matrix_starter_resolve_font_stylesheet();
  if ($is_local) {
    return $hints;
  }
  if ('preconnect' === $relation_type) {
    $hints[] = 'https://fonts.googleapis.com';
    $hints[] = 'https://fonts.gstatic.com';
  }
  return $hints;
}
add_filter('wp_resource_hints', 'matrix_starter_resource_hints', 10, 2);